# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AgentUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_index: int
    agent_address: int
    old_total_staked: int
    new_total_staked: int
    session_address: int
    block_timestamp: int
