# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class AgentUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_index: int
    agent_address: int
    old_total_deposited: int
    new_total_deposited: int
    session_address: int
    block_timestamp: int
