# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FeeRecipientUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    previous_recipient: int
    new_recipient: int
    block_timestamp: int
