# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class GameOverPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    winning_agent_index: int
    burn_fee_amount: int
    platform_fee_amount: int
    total_fees_amount: int
    total_rewards: int
    block_timestamp: int
