# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class GameSuspendedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_timestamp: int
