# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class GameInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: int
    user_stake_token_address: int
    token_win_condition_address: int
    token_win_condition_threshold: int
    burn_fee_percentage: int
    platform_fee_percentage: int
    fee_recipient: int
    number_of_stake_windows: int
    number_of_agents: int
    block_timestamp: int
