# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class GameInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: int
    user_deposit_token_address: int
    token_win_condition_address: int
    token_win_condition_threshold: int
    burn_fee_percentage: int
    platform_fee_percentage: int
    fee_recipient: int
    number_of_agents: int
    block_timestamp: int
