# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class StakeWindowCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    window_index: int
    start_time: int
    end_time: int
    block_timestamp: int
