# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class UserDepositedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user: int
    agent_index: int
    amount: int
    old_score: int
    new_score: int
    block_timestamp: int
