# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class BurnPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sender: int
    amount0: int
    amount1: int
    balance0: int
    balance1: int
    reserve0: int
    reserve1: int
    user_liquidity: int
    total_liquidity: int
    total_supply: int
    factory_address: int
    block_timestamp: int
