# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class KLastUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    old_klast: int
    new_klast: int
    pair_address: int
    block_timestamp: int
