# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PriceAccumulatorUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    price_0_cumulative_last: int
    price_1_cumulative_last: int
    pair_address: int
    block_timestamp: int
