# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ReserveUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    old_reserve0: int
    old_reserve1: int
    new_reserve0: int
    new_reserve1: int
    pair_address: int
    block_timestamp: int
