# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class AddedToWhitelistPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: int
    block_timestamp: int
