# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ClaimIntervalUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    old_interval: int
    new_interval: int
    block_timestamp: int
