# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FaucetInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    faucet_address: int
    owner: int
    claim_interval: int
    game_session_id: int
    block_timestamp: int
