# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class LastClaimUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    previous_timestamp: int
    new_timestamp: int
    block_timestamp: int
