# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TokenAddedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token: int
    amount: int
    claim_amount: int
    block_timestamp: int
