# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class TokenAddedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token: int
    amount: int
    claim_amount: int
    block_timestamp: int
