spec_version: 3.0
package: defi_space_indexer

logging: INFO

database:
  kind: postgres
  host: ${POSTGRES_HOST:-db}
  port: 5432
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: http://${HASURA_HOST:-hasura}:8080
  admin_secret: ${HASURA_SECRET}
  allow_aggregations: ${HASURA_ALLOW_AGGREGATIONS:-true}
  select_limit: ${HASURA_SELECT_LIMIT:-10000}
  camel_case: ${HASURA_CAMEL_CASE:-true}

datasources:
  # subsquid:
  #   kind: starknet.subsquid
  #   url: ${SUBSQUID_URL:-https://v2.archive.subsquid.io/network/starknet-mainnet}
  node:
    kind: starknet.node
    url: ${NODE_URL}/${NODE_API_KEY}
    http:
      ratelimit_rate: 3
      ratelimit_period: 1
      ratelimit_sleep: 1

contracts:
  amm_factory:
    kind: starknet
    address: ${AMM_FACTORY_ADDRESS}
    typename: amm_factory

  amm_pair:
    kind: starknet
    address: ${AMM_PAIR_ADDRESS} # Template
    typename: amm_pair

  farm_factory:
    kind: starknet
    address: ${FARM_FACTORY_ADDRESS}
    typename: farming_factory

  farm:
    kind: starknet
    address: ${FARM_ADDRESS} # Template
    typename: farming_farm

  game_factory:
    kind: starknet
    address: ${GAME_FACTORY_ADDRESS}
    typename: game_factory

  game_session:
    kind: starknet
    address: ${GAME_SESSION_ADDRESS} # Template
    typename: game_session

  faucet:
    kind: starknet
    address: ${FAUCET_ADDRESS}
    typename: faucet

indexes:
  amm_factory_events:
    kind: starknet.events
    first_level: ${AMM_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_pair_created
        contract: amm_factory
        name: PairCreated
      - callback: on_fees_receiver_updated
        contract: amm_factory
        name: FeesReceiverUpdated
      - callback: on_owner_updated
        contract: amm_factory
        name: OwnerUpdated
      - callback: on_pair_contract_class_hash_updated
        contract: amm_factory
        name: PairContractClassHashUpdated
      - callback: on_factory_initialized
        contract: amm_factory
        name: FactoryInitialized
      - callback: on_amm_factory_config_updated
        contract: amm_factory
        name: ConfigUpdated

  farm_factory_events:
    kind: starknet.events
    first_level: ${FARM_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_farm_created
        contract: farm_factory
        name: FarmCreated
      - callback: on_farm_factory_ownership_transferred
        contract: farm_factory
        name: OwnershipTransferred
      - callback: on_farm_class_hash_updated
        contract: farm_factory
        name: FarmClassHashUpdated
      - callback: on_farm_factory_initialized
        contract: farm_factory
        name: FarmFactoryInitialized
      - callback: on_farm_factory_config_updated
        contract: farm_factory
        name: ConfigUpdated

  game_factory_events:
    kind: starknet.events
    first_level: ${GAME_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_game_factory_initialized
        contract: game_factory
        name: FactoryInitialized
      - callback: on_game_session_created
        contract: game_factory
        name: GameSessionCreated
      - callback: on_game_ownership_transferred
        contract: game_factory
        name: OwnershipTransferred
      - callback: on_game_session_class_hash_updated
        contract: game_factory
        name: GameSessionClassHashUpdated
      - callback: on_game_factory_config_updated
        contract: game_factory
        name: ConfigUpdated

  faucet_events:
    kind: starknet.events
    first_level: ${FAUCET_FIRST_LEVEL}
    datasources:
      - node
    handlers:
      - callback: on_faucet_initialized
        contract: faucet
        name: FaucetInitialized
      - callback: on_token_claimed
        contract: faucet
        name: Claim
      - callback: on_user_whitelisted
        contract: faucet
        name: AddedToWhitelist
      - callback: on_token_added
        contract: faucet
        name: TokenAdded
      - callback: on_token_removed
        contract: faucet
        name: TokenRemoved
      - callback: on_user_removed_from_whitelist
        contract: faucet
        name: RemovedFromWhitelist
      - callback: on_claim_interval_updated
        contract: faucet
        name: ClaimIntervalUpdated
      - callback: on_faucet_ownership_transferred
        contract: faucet
        name: OwnershipTransferred
      - callback: on_last_claim_updated
        contract: faucet
        name: LastClaimUpdated
      - callback: on_config_updated
        contract: faucet
        name: ConfigUpdated

  # ---- For code generation only ----
  # farm_events_init:
  #   template: farm_events
  #   values:
  #     contract: farm
  # pair_events_init:
  #   template: pair_events
  #   values:
  #     contract: amm_pair
  # game_session_events_init:
  #   template: game_session_events
  #   values:
  #     contract: game_session

templates:
  pair_events:
    kind: starknet.events
    first_level: ${AMM_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_mint
        contract: <contract>
        name: Mint
      - callback: on_burn
        contract: <contract>
        name: Burn
      - callback: on_swap
        contract: <contract>
        name: Swap
      - callback: on_sync
        contract: <contract>
        name: Sync
      - callback: on_skim
        contract: <contract>
        name: Skim
      - callback: on_pair_config_updated
        contract: <contract>
        name: ConfigUpdated
      - callback: on_reserve_updated
        contract: <contract>
        name: ReserveUpdated
      - callback: on_klast_updated
        contract: <contract>
        name: KLastUpdated
      - callback: on_price_accumulator_updated
        contract: <contract>
        name: PriceAccumulatorUpdated

  farm_events:
    kind: starknet.events
    first_level: ${FARM_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_deposit
        contract: <contract>
        name: Deposit
      - callback: on_withdraw
        contract: <contract>
        name: Withdraw
      - callback: on_harvest
        contract: <contract>
        name: Harvest
      - callback: on_reward_added
        contract: <contract>
        name: RewardAdded
      - callback: on_erc20_recovered
        contract: <contract>
        name: ERC20Recovered
      - callback: on_unallocated_rewards_claimed
        contract: <contract>
        name: UnallocatedRewardsClaimed
      - callback: on_penalty_receiver_updated
        contract: <contract>
        name: PenaltyReceiverUpdated
      - callback: on_rewarder_added
        contract: <contract>
        name: RewarderAdded
      - callback: on_rewarder_removed
        contract: <contract>
        name: RewarderRemoved
      - callback: on_farm_ownership_transferred
        contract: <contract>
        name: OwnershipTransferred
      - callback: on_farm_config_updated
        contract: <contract>
        name: ConfigUpdated
      - callback: on_reward_per_token_updated
        contract: <contract>
        name: RewardPerTokenUpdated
      - callback: on_reward_state_updated
        contract: <contract>
        name: RewardStateUpdated
      - callback: on_penalty_end_time_updated
        contract: <contract>
        name: PenaltyEndTimeUpdated
      - callback: on_unallocated_rewards_updated
        contract: <contract>
        name: UnallocatedRewardsUpdated

  game_session_events:
    kind: starknet.events
    first_level: ${GAME_FACTORY_FIRST_LEVEL}
    datasources:
      # - subsquid
      - node
    handlers:
      - callback: on_game_suspended
        contract: <contract>
        name: GameSuspended
      - callback: on_game_over
        contract: <contract>
        name: GameOver
      - callback: on_stake_window_created
        contract: <contract>
        name: StakeWindowCreated
      - callback: on_user_staked
        contract: <contract>
        name: UserStaked
      - callback: on_user_unstaked
        contract: <contract>
        name: UserUnstaked
      - callback: on_emergency_withdraw
        contract: <contract>
        name: EmergencyWithdraw
      - callback: on_rewards_claimed
        contract: <contract>
        name: RewardsClaimed
      - callback: on_fee_recipient_updated
        contract: <contract>
        name: FeeRecipientUpdated
      - callback: on_game_initialized
        contract: <contract>
        name: GameInitialized
      - callback: on_game_config_updated
        contract: <contract>
        name: ConfigUpdated
      - callback: on_agent_updated
        contract: <contract>
        name: AgentUpdated
      - callback: on_agent_created
        contract: <contract>
        name: AgentCreated

hooks:
  calculate_game_metrics:
    callback: calculate_game_metrics
    atomic: False
    args:
      factory_address: str | None
      session_address: str | None
  active_staking_window:
    callback: active_staking_window
    atomic: False
    args:
      update_all: bool
      session_address: str | None

jobs:
  game_metrics_update:
    hook: calculate_game_metrics
    interval: 60
  active_staking_window:
    hook: active_staking_window
    interval: 30
    args:
      update_all: true
      session_address: null