# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FactoryInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    factory_address: int
    owner: int
    fee_to: int
    pair_contract_class_hash: int
    block_timestamp: int
