# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FarmFactoryInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    farm_factory: int
    owner: int
    farm_class_hash: int
    block_timestamp: int
