# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FarmCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    farm: int
    lp_token: int
    farm_factory: int
    penalty_duration: int
    withdraw_penalty: int
    multiplier: int
    penalty_receiver: int
    farm_index: int
    farm_count: int
    game_session_id: int
    block_timestamp: int
