# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FaucetClassHashUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    old_hash: int
    new_hash: int
    faucet_factory: int
    block_timestamp: int
