# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from typing import Union


class FaucetCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    faucet: int
    game_session_id: Union[str, int]
    faucet_factory: int
    claim_interval: int
    faucet_index: int
    faucet_count: int
    block_timestamp: int 