# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FaucetFactoryInitializedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    faucet_factory: int
    owner: int
    faucet_class_hash: int
    block_timestamp: int
