# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class FaucetCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    faucet: int
    game_session_id: int
    faucet_factory: int
    claim_interval: int
    faucet_index: int
    faucet_count: int
    block_timestamp: int
