# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class GameSessionCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    game_session: int
    token_win_condition: int
    stake_token: int
    token_win_condition_threshold: int
    burn_fee_percentage: int
    platform_fee_percentage: int
    creator: int
    factory_address: int
    session_index: int
    total_sessions: int
    block_timestamp: int
