# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class DepositPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    staked_amount: int
    total_staked: int
    user_staked: int
    multiplier: int
    penalty_end_time: int
    block_timestamp: int
