# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class ERC20RecoveredPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_address: int
    token_amount: int
    to: int
    block_timestamp: int
