# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PenaltyEndTimeUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    old_end_time: int
    new_end_time: int
    block_timestamp: int
