# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class PenaltyReceiverUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    previous_receiver: int
    new_receiver: int
    block_timestamp: int
