# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RewardStateUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_address: int
    reward_token: int
    reward_per_token_paid: int
    rewards: int
    block_timestamp: int
