# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class RewardPerTokenUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reward_token: int
    previous_value: int
    new_value: int
    block_timestamp: int
