# generated by DipDup 8.2.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class UnallocatedRewardsUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reward_token: int
    previous_amount: int
    new_amount: int
    block_timestamp: int
