# generated by DipDup 8.4.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class UnallocatedRewardsClaimedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reward_token: int
    amount: int
    claimer: int
    unallocated_rewards: int
    block_timestamp: int
